import { CollectionConfig } from 'payload';

const Products: CollectionConfig = {
  slug: 'products',

  access: {
    // Everyone must filter by their own tenant
    read: ({ req }) => {
      if (!req.user) return false;

      return {
        tenant: { equals: req.user.tenant },
      };
    },

    // Only admintoko can create directly — kasir must use ActionRequests
    create: ({ req }) => {
      if (!req.user) return false;
      return req.user.role === 'admintoko' || req.user.role === 'superadmin';
    },

    // Only admintoko can update directly — kasir must use ActionRequests
    update: ({ req }) => {
      if (!req.user) return false;

      if (req.user.role === 'admintoko' || req.user.role === 'superadmin') {
        return {
          tenant: { equals: req.user.tenant },
        };
      }

      return false;
    },

    // Only admintoko can delete directly
    delete: ({ req }) => {
      if (!req.user) return false;

      if (req.user.role === 'admintoko' || req.user.role === 'superadmin') {
        return {
          tenant: { equals: req.user.tenant },
        };
      }

      return false;
    },
  },

  fields: [
    // Tenant
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      required: false,
      index: true,
    },

    { name: 'nama', type: 'text', required: true },

    {
      name: 'sku',
      type: 'text',
      admin: {
        readOnly: true, // SKU autogenerated
      },
    },

    {
      name: 'kategori',
      type: 'select',
      required: true,
      defaultValue: 'other',
      options: [
        { label: 'Makanan', value: 'makanan' },
        { label: 'Minuman', value: 'minuman' },
        { label: 'Snack', value: 'snack' },
        { label: 'Lainnya', value: 'other' },
      ],
    },

    { name: 'harga', type: 'number', required: true },

    {
      name: 'stok',
      type: 'number',
      required: true,
      defaultValue: 0,
      min: 0,
    },

    { name: 'gambar', type: 'upload', relationTo: 'media' },
    { name: 'deskripsi', type: 'textarea' },

    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'aktif',
      options: [
        { label: 'Aktif', value: 'aktif' },
        { label: 'Nonaktif', value: 'nonaktif' },
      ],
    },
  ],

  hooks: {
    beforeChange: [
      async ({ data, req, operation }) => {
        // Auto-SKU logic
        if (operation === 'create') {
          const name = data.nama || '';

          const base = name
            .toUpperCase()
            .replace(/[^A-Z0-9]+/g, '-')
            .replace(/^-+|-+$/g, '');

          const existing = await req.payload.find({
            collection: 'products',
            where: {
              tenant: { equals: data.tenant },
              sku: { like: `${base}` },
            },
          });

          const next = (existing.totalDocs + 1)
            .toString()
            .padStart(3, '0');

          data.sku = `${base}-${next}`;
        }

        return data;
      },
    ],
  },
};

export default Products;
