import { NextResponse } from 'next/server'
import payload from 'payload'

export async function POST(req: Request) {
  try {
    const body = await req.json()

    const {
      businessField,
      businessType,
      adminName,
      address,
      email,
      phone,
      businessName,
      password,
    } = body

    // 1. Create the user (OTP is automatically generated by Users hook)
    await payload.create({
      collection: 'users',
      data: {
        email,
        password,
        role: 'admintoko',
        adminName,
        phone,
        businessName,
        businessField,
        businessType,
        address,
        isBusinessUser: true,
      },
    })

    // 2. Response to frontend
    return NextResponse.json({ success: true })
  } catch (e: unknown) {
    const errorMessage = e instanceof Error ? e.message : 'Unknown error'
    console.error('register error:', errorMessage)

    return NextResponse.json({ success: false, message: errorMessage }, { status: 500 })
  }
}
