/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  integer,
  timestamp,
  boolean,
  numeric,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['superadmin', 'admintoko', 'kasir'])
export const enum_promos_available_days = pgEnum('enum_promos_available_days', [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
])
export const enum_promos_order_type = pgEnum('enum_promos_order_type', [
  'dinein',
  'takeaway',
  'delivery',
])
export const enum_promos_kategori = pgEnum('enum_promos_kategori', [
  'all',
  'product',
  'min_purchase',
])
export const enum_promos_promo_type = pgEnum('enum_promos_promo_type', ['discount', 'bxgy'])
export const enum_promos_tipe_diskon = pgEnum('enum_promos_tipe_diskon', ['percent', 'nominal'])
export const enum_promos_stacking = pgEnum('enum_promos_stacking', ['no', 'yes', 'single'])
export const enum_promos_limit_customer = pgEnum('enum_promos_limit_customer', [
  'unlimited',
  'one',
  'multiple',
])
export const enum_promos_status = pgEnum('enum_promos_status', ['Aktif', 'Nonaktif'])
export const enum_products_status = pgEnum('enum_products_status', ['aktif', 'nonaktif'])
export const enum_transactions_status = pgEnum('enum_transactions_status', [
  'proses',
  'selesai',
  'batal',
])
export const enum_transactions_cara_bayar = pgEnum('enum_transactions_cara_bayar', [
  'cash',
  'non_cash',
])
export const enum_payments_status = pgEnum('enum_payments_status', [
  'pending',
  'paid',
  'expired',
  'failed',
])
export const enum_notifications_type = pgEnum('enum_notifications_type', [
  'transaksi',
  'produk',
  'promo',
  'reservasi',
  'peringatan',
])
export const enum_notifications_icon = pgEnum('enum_notifications_icon', [
  'berhasil',
  'gagal',
  'warning',
  'baru',
])
export const enum_notifications_tipe = pgEnum('enum_notifications_tipe', [
  'low_stock',
  'out_of_stock',
  'promo_low_quota',
  'promo_out_quota',
  'trx_success',
  'trx_cancel',
  'reservation_new',
  'reservation_confirm',
  'reservation_cancel',
  'product_new',
])
export const enum_reservations_jenis_kelamin = pgEnum('enum_reservations_jenis_kelamin', [
  'laki-laki',
  'perempuan',
])
export const enum_reservations_status_pembayaran = pgEnum('enum_reservations_status_pembayaran', [
  'unpaid',
  'partial',
  'paid',
])
export const enum_reservations_metode_pembayaran = pgEnum('enum_reservations_metode_pembayaran', [
  'tunai',
  'ewallet',
  'qris',
  'va',
])
export const enum_reservations_status = pgEnum('enum_reservations_status', [
  'menunggu',
  'dikonfirmasi',
  'checkin',
  'selesai',
  'noshow',
])
export const enum_tables_lantai = pgEnum('enum_tables_lantai', [
  'lantai_1',
  'lantai_2',
  'lantai_3',
  'rooftop',
])
export const enum_tables_area = pgEnum('enum_tables_area', ['vip', 'indoor', 'outdoor', 'smoking'])
export const enum_tables_bentuk = pgEnum('enum_tables_bentuk', ['kotak', 'bulat'])
export const enum_payment_methods_type = pgEnum('enum_payment_methods_type', [
  'cash',
  'bank_transfer',
  'qris',
  'ewallet',
])
export const enum_shifts_shift_name = pgEnum('enum_shifts_shift_name', ['Pagi', 'Siang', 'Malam'])
export const enum_shifts_status = pgEnum('enum_shifts_status', ['open', 'closed'])

export const tenants = pgTable(
  'tenants',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    domain: varchar('domain'),
    createdBy: integer('created_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('tenants_created_by_idx').on(columns.createdBy),
    index('tenants_updated_at_idx').on(columns.updatedAt),
    index('tenants_created_at_idx').on(columns.createdAt),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    role: enum_users_role('role').default('kasir'),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    emailVerified: boolean('email_verified').default(false),
    otp: varchar('otp'),
    otpExpiration: timestamp('otp_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    phone: varchar('phone'),
    businessName: varchar('business_name'),
    tempBusinessName: varchar('temp_business_name'),
    adminName: varchar('admin_name'),
    businessField: varchar('business_field'),
    businessType: varchar('business_type'),
    address: varchar('address'),
    isBusinessUser: boolean('is_business_user').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_tenant_idx').on(columns.tenant),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const promos_available_days = pgTable(
  'promos_available_days',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_promos_available_days('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('promos_available_days_order_idx').on(columns.order),
    index('promos_available_days_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [promos.id],
      name: 'promos_available_days_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const promos_order_type = pgTable(
  'promos_order_type',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_promos_order_type('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('promos_order_type_order_idx').on(columns.order),
    index('promos_order_type_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [promos.id],
      name: 'promos_order_type_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const promos = pgTable(
  'promos',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    nama: varchar('nama').notNull(),
    kode: varchar('kode').notNull(),
    showOnDashboard: boolean('show_on_dashboard').default(true),
    banner: integer('banner_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    mulai: timestamp('mulai', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    akhir: timestamp('akhir', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    startTime: varchar('start_time'),
    endTime: varchar('end_time'),
    kategori: enum_promos_kategori('kategori').notNull().default('all'),
    produk: integer('produk_id').references(() => products.id, {
      onDelete: 'set null',
    }),
    minPembelian: numeric('min_pembelian', { mode: 'number' }),
    promoType: enum_promos_promo_type('promo_type').notNull().default('discount'),
    tipeDiskon: enum_promos_tipe_diskon('tipe_diskon').default('percent'),
    nilaiDiskon: numeric('nilai_diskon', { mode: 'number' }),
    buyQuantity: numeric('buy_quantity', { mode: 'number' }),
    freeQuantity: numeric('free_quantity', { mode: 'number' }),
    isMultiple: boolean('is_multiple').default(true),
    useQuota: boolean('use_quota').default(false),
    kuota: numeric('kuota', { mode: 'number' }),
    kuotaUsed: numeric('kuota_used', { mode: 'number' }).default(0),
    stacking: enum_promos_stacking('stacking').default('no'),
    limitCustomer: enum_promos_limit_customer('limit_customer').default('unlimited'),
    status: enum_promos_status('status').default('Aktif'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('promos_tenant_idx').on(columns.tenant),
    index('promos_banner_idx').on(columns.banner),
    index('promos_produk_idx').on(columns.produk),
    index('promos_updated_at_idx').on(columns.updatedAt),
    index('promos_created_at_idx').on(columns.createdAt),
  ],
)

export const promos_rels = pgTable(
  'promos_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    productsID: integer('products_id'),
  },
  (columns) => [
    index('promos_rels_order_idx').on(columns.order),
    index('promos_rels_parent_idx').on(columns.parent),
    index('promos_rels_path_idx').on(columns.path),
    index('promos_rels_products_id_idx').on(columns.productsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [promos.id],
      name: 'promos_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'promos_rels_products_fk',
    }).onDelete('cascade'),
  ],
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    nama: varchar('nama').notNull(),
    useAutoSku: boolean('use_auto_sku').default(true),
    sku: varchar('sku'),
    kategori: integer('kategori_id')
      .notNull()
      .references(() => categories.id, {
        onDelete: 'set null',
      }),
    harga: numeric('harga', { mode: 'number' }).notNull(),
    stok: numeric('stok', { mode: 'number' }).notNull().default(0),
    gambar: integer('gambar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    deskripsi: varchar('deskripsi'),
    status: enum_products_status('status').notNull().default('aktif'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('products_tenant_idx').on(columns.tenant),
    index('products_kategori_idx').on(columns.kategori),
    index('products_gambar_idx').on(columns.gambar),
    index('products_updated_at_idx').on(columns.updatedAt),
    index('products_created_at_idx').on(columns.createdAt),
  ],
)

export const transactions_items = pgTable(
  'transactions_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    nama: varchar('nama').notNull(),
    harga: numeric('harga', { mode: 'number' }).notNull(),
    qty: numeric('qty', { mode: 'number' }).notNull(),
  },
  (columns) => [
    index('transactions_items_order_idx').on(columns._order),
    index('transactions_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [transactions.id],
      name: 'transactions_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const transactions = pgTable(
  'transactions',
  {
    id: serial('id').primaryKey(),
    noPesanan: varchar('no_pesanan'),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    namaKasir: varchar('nama_kasir').notNull(),
    namaPelanggan: varchar('nama_pelanggan'),
    subtotal: numeric('subtotal', { mode: 'number' }).notNull(),
    pajak: numeric('pajak', { mode: 'number' }).notNull(),
    discount: numeric('discount', { mode: 'number' }).default(0),
    total: numeric('total', { mode: 'number' }).notNull(),
    status: enum_transactions_status('status').default('proses'),
    caraBayar: enum_transactions_cara_bayar('cara_bayar').notNull().default('cash'),
    paymentMethod: integer('payment_method_id').references(() => payment_methods.id, {
      onDelete: 'set null',
    }),
    bayar: numeric('bayar', { mode: 'number' }),
    kembalian: numeric('kembalian', { mode: 'number' }),
    waktu: timestamp('waktu', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('transactions_no_pesanan_idx').on(columns.noPesanan),
    index('transactions_tenant_idx').on(columns.tenant),
    index('transactions_payment_method_idx').on(columns.paymentMethod),
    index('transactions_updated_at_idx').on(columns.updatedAt),
    index('transactions_created_at_idx').on(columns.createdAt),
  ],
)

export const payments = pgTable(
  'payments',
  {
    id: serial('id').primaryKey(),
    orderId: varchar('order_id').notNull(),
    method: integer('method_id').references(() => payment_methods.id, {
      onDelete: 'set null',
    }),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    status: enum_payments_status('status').default('pending'),
    reference: varchar('reference'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payments_method_idx').on(columns.method),
    index('payments_updated_at_idx').on(columns.updatedAt),
    index('payments_created_at_idx').on(columns.createdAt),
  ],
)

export const notifications = pgTable(
  'notifications',
  {
    id: serial('id').primaryKey(),
    type: enum_notifications_type('type').notNull(),
    icon: enum_notifications_icon('icon').notNull(),
    tipe: enum_notifications_tipe('tipe').notNull(),
    title: varchar('title').notNull(),
    message: varchar('message').notNull(),
    isRead: boolean('is_read').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('notifications_updated_at_idx').on(columns.updatedAt),
    index('notifications_created_at_idx').on(columns.createdAt),
  ],
)

export const reservations = pgTable(
  'reservations',
  {
    id: serial('id').primaryKey(),
    kodeReservasi: varchar('kode_reservasi'),
    waktuReservasi: timestamp('waktu_reservasi', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    namaPelanggan: varchar('nama_pelanggan').notNull(),
    jenisKelamin: enum_reservations_jenis_kelamin('jenis_kelamin').notNull(),
    noTelepon: varchar('no_telepon').notNull(),
    email: varchar('email'),
    tanggal: timestamp('tanggal', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    jamMulai: varchar('jam_mulai').notNull(),
    jamSelesai: varchar('jam_selesai').notNull(),
    durasiMenit: numeric('durasi_menit', { mode: 'number' }),
    pax: numeric('pax', { mode: 'number' }).notNull(),
    deposit: numeric('deposit', { mode: 'number' }).default(0),
    totalTagihan: numeric('total_tagihan', { mode: 'number' }),
    statusPembayaran: enum_reservations_status_pembayaran('status_pembayaran').default('unpaid'),
    metodePembayaran: enum_reservations_metode_pembayaran('metode_pembayaran'),
    meja: integer('meja_id')
      .notNull()
      .references(() => tables.id, {
        onDelete: 'set null',
      }),
    status: enum_reservations_status('status').default('menunggu'),
    kasir: integer('kasir_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    checkInAt: timestamp('check_in_at', { mode: 'string', withTimezone: true, precision: 3 }),
    checkOutAt: timestamp('check_out_at', { mode: 'string', withTimezone: true, precision: 3 }),
    catatan: varchar('catatan'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('reservations_kode_reservasi_idx').on(columns.kodeReservasi),
    index('reservations_meja_idx').on(columns.meja),
    index('reservations_kasir_idx').on(columns.kasir),
    index('reservations_updated_at_idx').on(columns.updatedAt),
    index('reservations_created_at_idx').on(columns.createdAt),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    nama: varchar('nama').notNull(),
    ikon: integer('ikon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('categories_ikon_idx').on(columns.ikon),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const store_settings_jam_buka = pgTable(
  'store_settings_jam_buka',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    hari: varchar('hari'),
    buka: boolean('buka'),
    fullDay: boolean('full_day'),
    jamBuka: varchar('jam_buka'),
    jamTutup: varchar('jam_tutup'),
  },
  (columns) => [
    index('store_settings_jam_buka_order_idx').on(columns._order),
    index('store_settings_jam_buka_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [store_settings.id],
      name: 'store_settings_jam_buka_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const store_settings = pgTable(
  'store_settings',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    storeName: varchar('store_name').notNull(),
    serviceCharge: boolean('service_charge').default(true),
    serviceChargePercentage: numeric('service_charge_percentage', { mode: 'number' }).default(10),
    pajak: boolean('pajak').default(true),
    pajakPercentage: numeric('pajak_percentage', { mode: 'number' }).default(10),
    struk_header: varchar('struk_header'),
    struk_footer: varchar('struk_footer'),
    struk_logo: integer('struk_logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    struk_paperSize: numeric('struk_paper_size', { mode: 'number' }).default(80),
    struk_options_infoToko: boolean('struk_options_info_toko'),
    struk_options_noNota: boolean('struk_options_no_nota'),
    struk_options_noTransaksi: boolean('struk_options_no_transaksi'),
    struk_options_jamTransaksi: boolean('struk_options_jam_transaksi'),
    struk_options_jamBuka: boolean('struk_options_jam_buka'),
    struk_options_infoTambahan: boolean('struk_options_info_tambahan'),
    struk_options_namaMeja: boolean('struk_options_nama_meja'),
    struk_options_modePenjualan: boolean('struk_options_mode_penjualan'),
    struk_options_pax: boolean('struk_options_pax'),
    struk_options_namaKasir: boolean('struk_options_nama_kasir'),
    struk_options_posmindOrder: boolean('struk_options_posmind_order'),
    struk_options_cetakKe: boolean('struk_options_cetak_ke'),
    struk_options_promoMenu: boolean('struk_options_promo_menu'),
    struk_options_pembulatan: boolean('struk_options_pembulatan'),
    struk_options_pajak: boolean('struk_options_pajak'),
    struk_options_service: boolean('struk_options_service'),
    struk_options_wifi: boolean('struk_options_wifi'),
    struk_options_powered: boolean('struk_options_powered'),
    dapur_paperSize: numeric('dapur_paper_size', { mode: 'number' }).default(80),
    dapur_options_noTransaksi: boolean('dapur_options_no_transaksi'),
    dapur_options_tanggalTransaksi: boolean('dapur_options_tanggal_transaksi'),
    dapur_options_jamTransaksi: boolean('dapur_options_jam_transaksi'),
    dapur_options_modePenjualan: boolean('dapur_options_mode_penjualan'),
    dapur_options_namaWaiter: boolean('dapur_options_nama_waiter'),
    dapur_options_namaWaiter2: boolean('dapur_options_nama_waiter2'),
    dapur_options_namaSender: boolean('dapur_options_nama_sender'),
    dapur_options_infoTambahan: boolean('dapur_options_info_tambahan'),
    dapur_options_namaMeja: boolean('dapur_options_nama_meja'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('store_settings_tenant_idx').on(columns.tenant),
    index('store_settings_struk_struk_logo_idx').on(columns.struk_logo),
    index('store_settings_updated_at_idx').on(columns.updatedAt),
    index('store_settings_created_at_idx').on(columns.createdAt),
  ],
)

export const tables = pgTable(
  'tables',
  {
    id: serial('id').primaryKey(),
    namaMeja: varchar('nama_meja').notNull(),
    kapasitas: numeric('kapasitas', { mode: 'number' }).notNull(),
    lantai: enum_tables_lantai('lantai').notNull(),
    area: enum_tables_area('area'),
    bentuk: enum_tables_bentuk('bentuk').default('kotak'),
    posisi_x: numeric('posisi_x', { mode: 'number' }).notNull(),
    posisi_y: numeric('posisi_y', { mode: 'number' }).notNull(),
    dpMeja: numeric('dp_meja', { mode: 'number' }).default(0),
    catatan: varchar('catatan'),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('tables_nama_meja_idx').on(columns.namaMeja),
    index('tables_tenant_idx').on(columns.tenant),
    index('tables_updated_at_idx').on(columns.updatedAt),
    index('tables_created_at_idx').on(columns.createdAt),
  ],
)

export const payment_methods = pgTable(
  'payment_methods',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    type: enum_payment_methods_type('type'),
    externalId: numeric('external_id', { mode: 'number' }),
    code: varchar('code'),
    isActive: boolean('is_active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payment_methods_updated_at_idx').on(columns.updatedAt),
    index('payment_methods_created_at_idx').on(columns.createdAt),
  ],
)

export const shifts = pgTable(
  'shifts',
  {
    id: serial('id').primaryKey(),
    shiftCode: varchar('shift_code'),
    shiftName: enum_shifts_shift_name('shift_name').notNull(),
    status: enum_shifts_status('status').default('open'),
    cashier: integer('cashier_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    cashierEmail: varchar('cashier_email'),
    openedAt: timestamp('opened_at', { mode: 'string', withTimezone: true, precision: 3 }),
    closedAt: timestamp('closed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    openingCash: numeric('opening_cash', { mode: 'number' }).notNull(),
    expectedCash: numeric('expected_cash', { mode: 'number' }).default(0),
    expectedNonCash: numeric('expected_non_cash', { mode: 'number' }).default(0),
    actualCash: numeric('actual_cash', { mode: 'number' }).default(0),
    actualNonCash: numeric('actual_non_cash', { mode: 'number' }).default(0),
    differenceCash: numeric('difference_cash', { mode: 'number' }),
    differenceNonCash: numeric('difference_non_cash', { mode: 'number' }),
    closingNote: varchar('closing_note'),
    isCashMatched: boolean('is_cash_matched'),
    isNonCashMatched: boolean('is_non_cash_matched'),
    closingAction: boolean('closing_action'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('shifts_shift_code_idx').on(columns.shiftCode),
    index('shifts_cashier_idx').on(columns.cashier),
    index('shifts_updated_at_idx').on(columns.updatedAt),
    index('shifts_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tenantsID: integer('tenants_id'),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    promosID: integer('promos_id'),
    productsID: integer('products_id'),
    transactionsID: integer('transactions_id'),
    paymentsID: integer('payments_id'),
    notificationsID: integer('notifications_id'),
    reservationsID: integer('reservations_id'),
    categoriesID: integer('categories_id'),
    storeSettingsID: integer('store_settings_id'),
    tablesID: integer('tables_id'),
    'payment-methodsID': integer('payment_methods_id'),
    shiftsID: integer('shifts_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_tenants_id_idx').on(columns.tenantsID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_promos_id_idx').on(columns.promosID),
    index('payload_locked_documents_rels_products_id_idx').on(columns.productsID),
    index('payload_locked_documents_rels_transactions_id_idx').on(columns.transactionsID),
    index('payload_locked_documents_rels_payments_id_idx').on(columns.paymentsID),
    index('payload_locked_documents_rels_notifications_id_idx').on(columns.notificationsID),
    index('payload_locked_documents_rels_reservations_id_idx').on(columns.reservationsID),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_store_settings_id_idx').on(columns.storeSettingsID),
    index('payload_locked_documents_rels_tables_id_idx').on(columns.tablesID),
    index('payload_locked_documents_rels_payment_methods_id_idx').on(columns['payment-methodsID']),
    index('payload_locked_documents_rels_shifts_id_idx').on(columns.shiftsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tenantsID']],
      foreignColumns: [tenants.id],
      name: 'payload_locked_documents_rels_tenants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['promosID']],
      foreignColumns: [promos.id],
      name: 'payload_locked_documents_rels_promos_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['transactionsID']],
      foreignColumns: [transactions.id],
      name: 'payload_locked_documents_rels_transactions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['paymentsID']],
      foreignColumns: [payments.id],
      name: 'payload_locked_documents_rels_payments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['notificationsID']],
      foreignColumns: [notifications.id],
      name: 'payload_locked_documents_rels_notifications_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['reservationsID']],
      foreignColumns: [reservations.id],
      name: 'payload_locked_documents_rels_reservations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['storeSettingsID']],
      foreignColumns: [store_settings.id],
      name: 'payload_locked_documents_rels_store_settings_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tablesID']],
      foreignColumns: [tables.id],
      name: 'payload_locked_documents_rels_tables_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payment-methodsID']],
      foreignColumns: [payment_methods.id],
      name: 'payload_locked_documents_rels_payment_methods_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['shiftsID']],
      foreignColumns: [shifts.id],
      name: 'payload_locked_documents_rels_shifts_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_tenants = relations(tenants, ({ one }) => ({
  createdBy: one(users, {
    fields: [tenants.createdBy],
    references: [users.id],
    relationName: 'createdBy',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [users.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_promos_available_days = relations(promos_available_days, ({ one }) => ({
  parent: one(promos, {
    fields: [promos_available_days.parent],
    references: [promos.id],
    relationName: 'availableDays',
  }),
}))
export const relations_promos_order_type = relations(promos_order_type, ({ one }) => ({
  parent: one(promos, {
    fields: [promos_order_type.parent],
    references: [promos.id],
    relationName: 'orderType',
  }),
}))
export const relations_promos_rels = relations(promos_rels, ({ one }) => ({
  parent: one(promos, {
    fields: [promos_rels.parent],
    references: [promos.id],
    relationName: '_rels',
  }),
  productsID: one(products, {
    fields: [promos_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
}))
export const relations_promos = relations(promos, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [promos.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  banner: one(media, {
    fields: [promos.banner],
    references: [media.id],
    relationName: 'banner',
  }),
  availableDays: many(promos_available_days, {
    relationName: 'availableDays',
  }),
  produk: one(products, {
    fields: [promos.produk],
    references: [products.id],
    relationName: 'produk',
  }),
  orderType: many(promos_order_type, {
    relationName: 'orderType',
  }),
  _rels: many(promos_rels, {
    relationName: '_rels',
  }),
}))
export const relations_products = relations(products, ({ one }) => ({
  tenant: one(tenants, {
    fields: [products.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  kategori: one(categories, {
    fields: [products.kategori],
    references: [categories.id],
    relationName: 'kategori',
  }),
  gambar: one(media, {
    fields: [products.gambar],
    references: [media.id],
    relationName: 'gambar',
  }),
}))
export const relations_transactions_items = relations(transactions_items, ({ one }) => ({
  _parentID: one(transactions, {
    fields: [transactions_items._parentID],
    references: [transactions.id],
    relationName: 'items',
  }),
}))
export const relations_transactions = relations(transactions, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [transactions.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  items: many(transactions_items, {
    relationName: 'items',
  }),
  paymentMethod: one(payment_methods, {
    fields: [transactions.paymentMethod],
    references: [payment_methods.id],
    relationName: 'paymentMethod',
  }),
}))
export const relations_payments = relations(payments, ({ one }) => ({
  method: one(payment_methods, {
    fields: [payments.method],
    references: [payment_methods.id],
    relationName: 'method',
  }),
}))
export const relations_notifications = relations(notifications, () => ({}))
export const relations_reservations = relations(reservations, ({ one }) => ({
  meja: one(tables, {
    fields: [reservations.meja],
    references: [tables.id],
    relationName: 'meja',
  }),
  kasir: one(users, {
    fields: [reservations.kasir],
    references: [users.id],
    relationName: 'kasir',
  }),
}))
export const relations_categories = relations(categories, ({ one }) => ({
  ikon: one(media, {
    fields: [categories.ikon],
    references: [media.id],
    relationName: 'ikon',
  }),
}))
export const relations_store_settings_jam_buka = relations(store_settings_jam_buka, ({ one }) => ({
  _parentID: one(store_settings, {
    fields: [store_settings_jam_buka._parentID],
    references: [store_settings.id],
    relationName: 'jamBuka',
  }),
}))
export const relations_store_settings = relations(store_settings, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [store_settings.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  jamBuka: many(store_settings_jam_buka, {
    relationName: 'jamBuka',
  }),
  struk_logo: one(media, {
    fields: [store_settings.struk_logo],
    references: [media.id],
    relationName: 'struk_logo',
  }),
}))
export const relations_tables = relations(tables, ({ one }) => ({
  tenant: one(tenants, {
    fields: [tables.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
}))
export const relations_payment_methods = relations(payment_methods, () => ({}))
export const relations_shifts = relations(shifts, ({ one }) => ({
  cashier: one(users, {
    fields: [shifts.cashier],
    references: [users.id],
    relationName: 'cashier',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    tenantsID: one(tenants, {
      fields: [payload_locked_documents_rels.tenantsID],
      references: [tenants.id],
      relationName: 'tenants',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    promosID: one(promos, {
      fields: [payload_locked_documents_rels.promosID],
      references: [promos.id],
      relationName: 'promos',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    transactionsID: one(transactions, {
      fields: [payload_locked_documents_rels.transactionsID],
      references: [transactions.id],
      relationName: 'transactions',
    }),
    paymentsID: one(payments, {
      fields: [payload_locked_documents_rels.paymentsID],
      references: [payments.id],
      relationName: 'payments',
    }),
    notificationsID: one(notifications, {
      fields: [payload_locked_documents_rels.notificationsID],
      references: [notifications.id],
      relationName: 'notifications',
    }),
    reservationsID: one(reservations, {
      fields: [payload_locked_documents_rels.reservationsID],
      references: [reservations.id],
      relationName: 'reservations',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    storeSettingsID: one(store_settings, {
      fields: [payload_locked_documents_rels.storeSettingsID],
      references: [store_settings.id],
      relationName: 'storeSettings',
    }),
    tablesID: one(tables, {
      fields: [payload_locked_documents_rels.tablesID],
      references: [tables.id],
      relationName: 'tables',
    }),
    'payment-methodsID': one(payment_methods, {
      fields: [payload_locked_documents_rels['payment-methodsID']],
      references: [payment_methods.id],
      relationName: 'payment-methods',
    }),
    shiftsID: one(shifts, {
      fields: [payload_locked_documents_rels.shiftsID],
      references: [shifts.id],
      relationName: 'shifts',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_promos_available_days: typeof enum_promos_available_days
  enum_promos_order_type: typeof enum_promos_order_type
  enum_promos_kategori: typeof enum_promos_kategori
  enum_promos_promo_type: typeof enum_promos_promo_type
  enum_promos_tipe_diskon: typeof enum_promos_tipe_diskon
  enum_promos_stacking: typeof enum_promos_stacking
  enum_promos_limit_customer: typeof enum_promos_limit_customer
  enum_promos_status: typeof enum_promos_status
  enum_products_status: typeof enum_products_status
  enum_transactions_status: typeof enum_transactions_status
  enum_transactions_cara_bayar: typeof enum_transactions_cara_bayar
  enum_payments_status: typeof enum_payments_status
  enum_notifications_type: typeof enum_notifications_type
  enum_notifications_icon: typeof enum_notifications_icon
  enum_notifications_tipe: typeof enum_notifications_tipe
  enum_reservations_jenis_kelamin: typeof enum_reservations_jenis_kelamin
  enum_reservations_status_pembayaran: typeof enum_reservations_status_pembayaran
  enum_reservations_metode_pembayaran: typeof enum_reservations_metode_pembayaran
  enum_reservations_status: typeof enum_reservations_status
  enum_tables_lantai: typeof enum_tables_lantai
  enum_tables_area: typeof enum_tables_area
  enum_tables_bentuk: typeof enum_tables_bentuk
  enum_payment_methods_type: typeof enum_payment_methods_type
  enum_shifts_shift_name: typeof enum_shifts_shift_name
  enum_shifts_status: typeof enum_shifts_status
  tenants: typeof tenants
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  promos_available_days: typeof promos_available_days
  promos_order_type: typeof promos_order_type
  promos: typeof promos
  promos_rels: typeof promos_rels
  products: typeof products
  transactions_items: typeof transactions_items
  transactions: typeof transactions
  payments: typeof payments
  notifications: typeof notifications
  reservations: typeof reservations
  categories: typeof categories
  store_settings_jam_buka: typeof store_settings_jam_buka
  store_settings: typeof store_settings
  tables: typeof tables
  payment_methods: typeof payment_methods
  shifts: typeof shifts
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_tenants: typeof relations_tenants
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_promos_available_days: typeof relations_promos_available_days
  relations_promos_order_type: typeof relations_promos_order_type
  relations_promos_rels: typeof relations_promos_rels
  relations_promos: typeof relations_promos
  relations_products: typeof relations_products
  relations_transactions_items: typeof relations_transactions_items
  relations_transactions: typeof relations_transactions
  relations_payments: typeof relations_payments
  relations_notifications: typeof relations_notifications
  relations_reservations: typeof relations_reservations
  relations_categories: typeof relations_categories
  relations_store_settings_jam_buka: typeof relations_store_settings_jam_buka
  relations_store_settings: typeof relations_store_settings
  relations_tables: typeof relations_tables
  relations_payment_methods: typeof relations_payment_methods
  relations_shifts: typeof relations_shifts
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
